Update japanese translation
gitblit/gitblit pull request #1398
Opened 2021-12-06 03:32 UTC by TakehideMorimoto

2021-12-06 19:11 UTC, flaix requested changes
Hi! This is awesome!

I found some issues in your files, so you may want to go over them again and make sure you have no duplicate keys, no incorrect keys and no empty definitions.

What is more, though, is a technical issue. Your changes are based on a rather old commit and then merged into your master. This way I cannot merge them. A merge request should always come from a separate branch, not from master. (And only contain the changes for one feature/topic.) So can you create a new branch on top of the current master of `gitblit/gitblit` and cherry-pick only the one commit 17da704 onto it? I do think that you will probably have to create a new merge request for it.

If you don't know how to do that, that is also not a problem. In that case you can also add a new commit to fix the issues and I will then create new commit from your commits for you.

Please be advised that several issues with language files have been fixed (see PR #1380), which also touched the Japanese properties file.

In any case, thank you very much for taking the time and improving the Japanase translation!

2021-12-08 03:45 UTC, TakehideMorimoto commented
Sorry. I will go over some issues that you point out, and make sure keys.
And I create new branch and new merge request another day.

2022-01-15 20:37 UTC, flaix commented on src/main/java/com/gitblit/wicket/GitBlitWebApp_ja.properties
> +#        そうなった場合、優先度を考えてコメントを削ったり、複数行のコメントを1行にしたりして減らすこと。
Deleted

2022-01-15 21:07 UTC, flaix commented on src/main/java/com/gitblit/wicket/GitBlitWebApp_ja.properties
> +gb.comment = \u30b3\u30e1\u30f3\u30c8
Deleted

2022-01-15 21:08 UTC, flaix commented on src/main/java/com/gitblit/wicket/GitBlitWebApp_ja.properties
> +gb.regexPermission = this permission is set from regular expression \"{0}\"
Deleted

2022-01-15 21:10 UTC, flaix commented on src/main/java/com/gitblit/wicket/GitBlitWebApp_ja.properties
> +#gb.destinationUrl = send to
All removed

2022-01-15 21:35 UTC, flaix commented on src/main/java/com/gitblit/wicket/GitBlitWebApp_ja.properties
> +gb.languagePreferenceDescription =
Filled in with English default

2022-01-15 21:35 UTC, flaix commented on src/main/java/com/gitblit/wicket/GitBlitWebApp_ja.properties
> +gb.displayNameDescription =
Filled in with English default

2022-01-15 23:41 UTC, flaix commented
I have fixed the submission and added it under a new commit to the main branch.
Closing this as done.

2022-01-15 23:41 UTC, closed without merging